-- ==========================================================================
-- AURA MENTOR V2 - SUPABASE POSTGRESQL SCHEMA & ROW-LEVEL SECURITY (RLS)
-- ==========================================================================
-- Kopiere dieses Skript und füge es in den SQL-Editor deines Supabase-Projekts ein,
-- um die Tabellen und Sicherheitsregeln für die "Real-Version" zu erstellen.

-- 1. Tabelle für Benutzer-Profile (Teen / Parent Rollen)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  role text not null check (role in ('teen', 'parent')),
  parent_code text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabelle für geschützte Chatnachrichten
create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  sender_role text not null check (sender_role in ('child', 'mentor')),
  text text not null,
  is_hidden_from_parent boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabelle für gebuchte Mentoring-Sitzungen (Kalender)
create table public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  day_num integer not null check (day_num >= 1 and day_num <= 31),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================================================
-- ROW-LEVEL SECURITY (RLS) AKTIVIEREN (Maximaler Zwei-Wege-Datenschutz!)
-- ==========================================================================
alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.appointments enable row level security;

-- Richtlinien (Policies) für Profile
create policy "Benutzer koennen ihr eigenes Profil lesen"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Benutzer koennen ihr eigenes Profil aktualisieren"
  on public.profiles for update
  using (auth.uid() = id);

create policy "Benutzer koennen Profile einfuegen"
  on public.profiles for insert
  with check (true);

-- Richtlinien für Chat-Nachrichten (Eltern duerfen keine Kindernachrichten vom Server laden!)
create policy "Teenager koennen alle eigenen Nachrichten lesen"
  on public.messages for select
  using (auth.uid() = user_id);

create policy "Eltern duerfen nur nicht-zensierte Mentor-Nachrichten lesen"
  on public.messages for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'parent'
      and profiles.parent_code = (
        select email from auth.users where id = messages.user_id
      )
    )
    and is_hidden_from_parent = false
  );

create policy "Benutzer duerfen eigene Nachrichten einfuegen"
  on public.messages for insert
  with check (auth.uid() = user_id);

-- Richtlinien für Kalendertermine
create policy "Benutzer koennen eigene Termine lesen"
  on public.appointments for select
  using (auth.uid() = user_id);

create policy "Benutzer koennen eigene Termine eintragen"
  on public.appointments for insert
  with check (auth.uid() = user_id);
